# fly.toml app configuration file generated for dascdiscord on 2025-08-17T12:11:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dascdiscord'
primary_region = 'mia'

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python bot.py"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[experimental]
  auto_rollback = true
