# fly.toml app configuration file generated for dune-ops-web on 2025-08-23T14:51:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dune-ops-web'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
